# Generated by Django 4.0.8 on 2022-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xvector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(unique=True, upload_to='')),
                ('column1', models.TextField(default='')),
                ('column2', models.TextField(default='')),
            ],
        ),
    ]
