# Generated by Django 4.0.8 on 2022-11-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xvectorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xvector',
            name='column3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='xvector',
            name='column4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='xvector',
            name='columns',
            field=models.TextField(default=''),
        ),
    ]
