# Generated by Django 4.0.8 on 2022-11-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xvectorapp', '0002_xvector_column3_xvector_column4_xvector_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xvector',
            old_name='columns',
            new_name='col',
        ),
    ]
